#!/bin/bash

# cn_start_beats script
# Chris Neal - v1.0 - July 2nd, 2023
# Based on the script by u/warkolm - https://www.reddit.com/r/unRAID/comments/8kvcti/elastic_beats_on_unraid_tute/
# SPECIFY PARAMETERS IN THE FOLLOWING FILE: /boot/config/plugins/user.scripts/scripts/cn_start_beats/prefs

# --- BEGIN MAIN SCRIPT ---

# Load preferences from file
source /boot/config/plugins/user.scripts/scripts/cn_start_beats/prefs

# Check if the variables in the prefs file are empty/nonexistent, and exit if true
checked_variables=("BEATS" "VER" "MAINDIR")

for var in "${checked_variables[@]}"; do
  if [[ -z "${!var}" ]]; then
	echo "Error: $var is not defined in the prefs file. Exiting..."
	exit 1
  fi
done

# Run each specified beat in the background 
for BEAT in "${BEATS[@]}"; do
	RUNDIR="$MAINDIR/$BEAT-$VER-linux-x86_64"
	nohup $RUNDIR/$BEAT --path.config $RUNDIR/ --path.logs $RUNDIR/logs/ 2>&1 &
done
