#!/bin/bash

### ----------- ###
### USER CONFIG ###
### ----------- ###

BEATS=('metricbeat' 'filebeat') ## Specify beats to start
VER="8.7.1" ## Specify version of beats
MAINDIR="/mnt/user/system/beats" ## Path containing the beats folders
