#!/bin/bash

# update_cn_scripts file catalog
# Chris Neal - v1.1 - July 3rd, 2023

# List of files to update
FILES=(
  "cn_nuisance_files/description"
  "cn_nuisance_files/name"
  "cn_nuisance_files/prefs_template"
  "cn_nuisance_files/script"

  "cn_start_beats/description"
  "cn_start_beats/name"
  "cn_start_beats/prefs_template"
  "cn_start_beats/script"

  "cn_tailscale_smbfix/description"
  "cn_tailscale_smbfix/name"
  "cn_tailscale_smbfix/script"
  
  "cn_wipe_free_space/description"
  "cn_wipe_free_space/name"
  "cn_wipe_free_space/prefs_template"
  "cn_wipe_free_space/script"
)

# List of directories to check and create if necessary
DIRECTORIES=(
  "cn_nuisance_files"
  "cn_start_beats"
  "cn_tailscale_smbfix"
  "cn_wipe_free_space"
)