#!/bin/bash

# shellshack_restart_containers script
# Chris Neal - v1.0 - August 15th, 2023
# SPECIFY PARAMETERS IN THE FOLLOWING FILE: /boot/config/plugins/user.scripts/scripts/shellshack_restart_containers/prefs

for container in "${docker_containers[@]}"; do
  echo "Restarting $container"
  docker restart "$container"
done
