#!/bin/bash

### ----------- ###
### USER CONFIG ###
### ----------- ###

docker_containers=('binhex-delugevpn' 'plex') ## Specify containers to restart -- TIP: run "docker ps -a" in a console to find container names